APP_TITLE = "DIIS-INVENTORY"
MONGODB_DB = "kampandb"


KAMPAN_HOST_URL = "https://inventory.psu.ac.th"
REDIS_URL = "redis://localhost:6379"

DAIRY_TIME_TO_SNAP_ITEM = "19:50"
DAIRY_TIME_TO_UPDATE_STATUS_PROCUREMENT = "00:01"

KAMPAN_EMAIL_SENDER_NAME = "DIIS INVENTORY"
DAIRY_TIME_TO_SEND_PAYMENT_NOTIFICATION = "00:10"
